# -*- coding: utf-8 -*-
"""3 tokenizators compare

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NCDctJJECTVzPKhh8QwDPlwtYBxcsDzQ
"""

# @title
!pip install bert-score
!pip install datasets
!pip install sentence-transformers datasets accelerate transformers wandb
!pip install sentence-transformers torch sklearn bert-score
!pip install sentencepiece
!pip install -q sentencepiece transformers sentence-transformers bert-score torch scikit-learn pandas numpy
!pip install -q pytorch-crf

# @title
# ============================================================
# paraphrase-multilingual-MiniLM-L12-v2 → STANDARD vs KAZ Unigram
# single-view (архитектура) + dual-view (clean + segmented Q→Q retrieval)
# MLM адаптациясы жоқ, метрикалары шынайырақ held-out бағалау
# ============================================================

# ENV
import os
os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"
os.environ["WANDB_DISABLED"] = "true"  # sentence-transformers → W&B өшіру

# !pip install -q -U "transformers>=4.41.0" "tokenizers>=0.15.2" \
#                   "sentence-transformers>=2.7.0" "sentencepiece>=0.1.99" "bert-score"

import time, random
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from torch.utils.data import DataLoader

import sentencepiece as spm
import json  # JSON датасетін оқу үшін
from bert_score import score as bertscore

from tokenizers import Tokenizer
from tokenizers.models import Unigram
from tokenizers.processors import TemplateProcessing
from tokenizers.pre_tokenizers import Metaspace as PreMS
from tokenizers.decoders import Metaspace as DecMS

from transformers import (
    PreTrainedTokenizerFast,
    set_seed,
    AutoTokenizer,          # Оригинал токенизаторды жүктеу үшін
)

from sentence_transformers import SentenceTransformer, InputExample, losses, models
from google.colab import drive
from sklearn.model_selection import train_test_split

# --------------------------
# 🔒 Seed (strict deterministic емес, бірақ тұрақты)
# --------------------------
SEED = 42
set_seed(SEED)
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

try:
    torch.use_deterministic_algorithms(False)
except Exception:
    pass

torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("🖥 DEVICE:", DEVICE)

# ============================================================
# QA деректері (орнына өз 5944 QA-ңды қоясың)
# =========================
# 0) QA деректері – JSON файлдан оқу
# =========================
# Күтілетін формат (line-delimited JSON):
# {"question": "...", "answer": "..."}
# {"question": "...", "answer": "..."}
# ...

DATA_JSON_PATH = "qa_data.json"  # керек болса /content/drive/... деп толық жолға ауыстырыңыз

if not Path(DATA_JSON_PATH).is_file():
    raise FileNotFoundError(f"QA JSON файлы табылмады: {DATA_JSON_PATH}")

print(f"📥 QA JSON файлдан жүктеу: {DATA_JSON_PATH}")

data = []
with open(DATA_JSON_PATH, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue

        # Соңында үтір тұрған болса, алып тастаймыз: {...},
        if line.endswith(","):
            line = line[:-1].strip()

        # Алдымен тікелей parse жасап көреміз
        try:
            obj = json.loads(line)
        except json.JSONDecodeError as e:
            # Егер Invalid \escape қатесі болса — backslash-тарды escape жасаймыз
            if "Invalid \\escape" in str(e):
                fixed_line = line.replace("\\", "\\\\")
                obj = json.loads(fixed_line)
            else:
                raise
        data.append(obj)

# Күтілетін формат: [{"question": "...", "answer": "..."}, ...]
qa_data = pd.DataFrame(data)
assert {"question", "answer"}.issubset(qa_data.columns), "JSON-да 'question' және 'answer' бағандары болуы тиіс."

print(f"📚 Барлық QA жазба саны: {len(qa_data)}")

# --------------------------
# TRAIN / TEST SPLIT (held-out)
# --------------------------
train_df, test_df = train_test_split(
    qa_data,
    test_size=0.1,      # Нақты жобада 5944 → ~595 тест
    random_state=SEED,
    shuffle=True,
)

train_questions = train_df["question"].tolist()
train_answers   = train_df["answer"].tolist()
test_questions  = test_df["question"].tolist()
test_answers    = test_df["answer"].tolist()

print(f"📊 TRAIN: {len(train_df)} | TEST: {len(test_df)}")

# =========================
# Жолдар
# =========================
drive.mount("/content/drive", force_remount=True)

PROJECT_DIR     = "/content/kz_minilm_st_direct_spm"
BASE_ST_DIR     = f"{PROJECT_DIR}/st_baseline_clean"   # стандартты модель каталогы
KZ_ST_DIR       = f"{PROJECT_DIR}/st_kaz_clean"        # KAZ модель каталогы
MT5_ST_DIR      = f"{PROJECT_DIR}/st_mt5_clean"        # mT5 токенизаторы бар модель
KK_TOK_DIR      = f"{PROJECT_DIR}/kk_tokenizer"        # KAZ токенизаторы
MT5_TOK_DIR     = f"{PROJECT_DIR}/mt5_tokenizer"       # mT5 токенизаторы

Path(PROJECT_DIR).mkdir(parents=True, exist_ok=True)
Path(BASE_ST_DIR).mkdir(parents=True, exist_ok=True)
Path(KZ_ST_DIR).mkdir(parents=True, exist_ok=True)
Path(MT5_ST_DIR).mkdir(parents=True, exist_ok=True)
Path(KK_TOK_DIR).mkdir(parents=True, exist_ok=True)
Path(MT5_TOK_DIR).mkdir(parents=True, exist_ok=True)

SENTENCE_T_NAME = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
MT5_MODEL_NAME  = "google/mt5-base"  # қажет болса small/large-қа ауыстыруға болады

# SPM .model жолын ТЕКСЕРІҢІЗ (Kazakh BPE)
spm_model_path = "/content/drive/MyDrive/kazakh_bpe/kazakh_bpe.model"
assert Path(spm_model_path).exists(), f"SPM model not found: {spm_model_path}"

# ============================================================
# A) BASELINE-CLEAN: стандартты MiniLM токенизаторы (single-view архитектура)
# ============================================================
print("\n=== [BASELINE-CLEAN] Standard MiniLM токенизаторы, single-view (arch), Q→Q ===")
baseline_model = SentenceTransformer(SENTENCE_T_NAME, device=DEVICE)
baseline_model.to(DEVICE)
baseline_model.eval()
baseline_model.save(BASE_ST_DIR)
print(f"💾 BASELINE-CLEAN модель сақталды: {BASE_ST_DIR}")

# Оригинал MiniLM токенизаторы
print("🔍 Оригинал MiniLM токенизаторын жүктеу:", SENTENCE_T_NAME)
base_tok = AutoTokenizer.from_pretrained(SENTENCE_T_NAME)
base_vocab = base_tok.get_vocab()            # token -> id
inv_base_vocab = {idx: tok for tok, idx in base_vocab.items()}

# ОРИГИНАЛ вокаб өлшемін encoder эмбеддингінен аламыз (қауіпсізірек)
tmp_model = SentenceTransformer(SENTENCE_T_NAME, device=DEVICE)
orig_vocab_size = tmp_model[0].auto_model.get_input_embeddings().num_embeddings
del tmp_model
print("🔢 Оригинал вокаб өлшемі (эмбеддингтен):", orig_vocab_size)

# baseline эмбеддингтері (mT5 үшін инициализацияда қолданамыз)
base_word_model  = baseline_model[0]  # SentenceTransformer ішіндегі Transformer модулі
base_auto_model  = base_word_model.auto_model
base_emb_layer   = base_auto_model.get_input_embeddings()
base_weight_full = base_emb_layer.weight.data.clone()   # [orig_vocab_size, dim]

def _encode_retr_std(texts, batch_size=32, normalize=False, do_segment=False):
    """
    BASELINE-CLEAN retrieval:
    - do_segment=False → clean view
    - do_segment=True  → SPM сегменттелген view (dual-view үшін)
    """
    if do_segment:
        texts = [segment_text(t) for t in texts]

    with torch.inference_mode():
        vecs = baseline_model.encode(
            texts,
            batch_size=batch_size,
            convert_to_numpy=True,
            normalize_embeddings=normalize
        )
    return vecs

# ============================================================
# B) KAZ-CLEAN: SPM(.model) → Unigram токенизаторы, single-view (архитектура)
#    Dual-view тек retrieval деңгейінде (clean + segmented Q→Q)
#    Жаңа SPM токендер pretrained эмбеддингтерден мағыналы инициализацияланады
# ============================================================
print("\n=== [KAZ-CLEAN] Kazakh Unigram tokenizer, single-view (arch), Q→Q ===")
print("🔤 SPM моделін жүктеу және Kazakh Unigram токенизаторын дайындау...")
sp = spm.SentencePieceProcessor()
sp.Load(spm_model_path)

def segment_text(text: str) -> str:
    """
    Kazakh SPM-ге негізделген субсөздік/морфологиялық сегментация.
    Нәтиже – SPM pieces бос орынмен бөлінген string.
    Бұл функция dual-view үшін БАРЛЫҚ модельде (BASELINE, KAZ, mT5) қолданылады.
    """
    if not isinstance(text, str):
        text = str(text)
    pieces = sp.encode_as_pieces(text)
    return " ".join(pieces)

# 1. Unigram вокабы: әуелі ОРИГИНАЛ токендер (дәл сол id тәртібімен)
vocab = []
for idx in range(orig_vocab_size):
    tok_str = inv_base_vocab.get(idx, None)
    if tok_str is None:
        tok_str = f"[UNUSED_{idx}]"
    vocab.append((tok_str, 0.0))  # score маңызды емес, тек салыстырмалы

# 2. SPM вокабынан ЖАҢА токендерді ғана үстінен қосамыз
get_score = getattr(sp, "GetScore", None)
spm_size = sp.GetPieceSize()
added = 0
new_pieces = []       # жаңа SPM токендердің реті (id mapping үшін)

for i in range(spm_size):
    piece = sp.IdToPiece(i)
    if piece in base_vocab:
        continue
    score = float(get_score(i)) if callable(get_score) else -1.0
    vocab.append((piece, score))
    new_pieces.append(piece)
    added += 1

print(f"➕ SPM-нен қосылған жаңа токендер саны: {added}")
print("🔢 Жаңа Unigram вокабының өлшемі:", len(vocab))

# 3. UNK id – оригинал токенизатордан
if base_tok.unk_token_id is not None:
    unk_id = base_tok.unk_token_id
else:
    unk_id = next(
        i for i, (t, _) in enumerate(vocab) if t in ("<unk>", "[UNK]")
    )

# 4. Unigram моделі
tok = Tokenizer(Unigram(vocab=vocab, unk_id=unk_id))

# 5. PreTokenizer/Decoder – мүмкін болса, оригинал backend-тен
backend = getattr(base_tok, "backend_tokenizer", None)
if backend is not None:
    if backend.normalizer is not None:
        tok.normalizer = backend.normalizer
    tok.pre_tokenizer = backend.pre_tokenizer
    tok.decoder = backend.decoder
else:
    try:
        tok.pre_tokenizer = PreMS("▁")
    except TypeError:
        tok.pre_tokenizer = PreMS()
    try:
        tok.decoder = DecMS("▁")
    except TypeError:
        tok.decoder = DecMS()

# 6. Арнайы токендер – оригиналдан
cls_tok = base_tok.cls_token or "[CLS]"
sep_tok = base_tok.sep_token or "[SEP]"
pad_tok = base_tok.pad_token or "[PAD]"
mask_tok = base_tok.mask_token or "[MASK]"
unk_tok_str = base_tok.unk_token or "<unk>"

tok.post_processor = TemplateProcessing(
    single=f"{cls_tok} $A {sep_tok}",
    pair=f"{cls_tok} $A {sep_tok} $B {sep_tok}",
    special_tokens=[
        (cls_tok, base_vocab[cls_tok]),
        (sep_tok, base_vocab[sep_tok]),
    ],
)

kk_tok = PreTrainedTokenizerFast(
    tokenizer_object=tok,
    unk_token=unk_tok_str,
    sep_token=sep_tok,
    pad_token=pad_tok,
    cls_token=cls_tok,
    mask_token=mask_tok,
)
kk_tok.model_max_length = getattr(base_tok, "model_max_length", 512)

print("✅ Kazakh Fast токенизатор дайын. Vocab size:", len(kk_tok))

kk_tok.save_pretrained(KK_TOK_DIR)
print("📝 Kazakh токенизатор файлдары жазылды →", KK_TOK_DIR)

print("⬇️ MiniLM encoder-ін жүктеу және Kazakh токенизаторымен байланыстыру:", SENTENCE_T_NAME)

word_embedding_model_kz = models.Transformer(
    SENTENCE_T_NAME,
    tokenizer_name_or_path=KK_TOK_DIR
)

# Вокаб өлшемін жаңа Kazakh токенизаторға бейімдеу
word_embedding_model_kz.auto_model.resize_token_embeddings(len(kk_tok))

# --- Жаңа Kazakh токендердің эмбеддингін мағыналы инициализациялау ---
auto_model_kz = word_embedding_model_kz.auto_model
emb_layer_kz = auto_model_kz.get_input_embeddings()

with torch.no_grad():
    weight_kz = emb_layer_kz.weight.data
    old_vocab_size = orig_vocab_size            # алғашқы бөлігін оригинал деп аламыз
    new_vocab_size = len(kk_tok)

    # Оригинал токендердің орташа нормасын есептейміз
    base_norms = weight_kz[:old_vocab_size].norm(dim=1)
    avg_norm = base_norms.mean().item()
    print(f"🔧 [KAZ] Жаңа токен эмбеддингтерін инициализациялау: {old_vocab_size} → {new_vocab_size}")
    print(f"🔧 [KAZ] Оригинал эмбеддинг нормаларының орташа мәні: {avg_norm:.4f}")

    for new_id in range(old_vocab_size, new_vocab_size):
        idx_in_new = new_id - old_vocab_size
        if idx_in_new < 0 or idx_in_new >= len(new_pieces):
            continue

        piece = new_pieces[idx_in_new]         # мысалы: '▁Бағдарлама@@'
        # SPM piece → адамша текст
        piece_text = piece.replace("▁", " ").strip()
        if not piece_text:
            continue

        # 1) piece_text-ті стандартты токенизатормен токенизациялау
        base_ids = base_tok(
            piece_text,
            add_special_tokens=False
        )["input_ids"]
        base_ids = [i for i in base_ids if i < old_vocab_size]

        # 2) Егер бәрібір бос болса – символ деңгей fall-back
        if len(base_ids) == 0:
            chars = list(piece_text)
            for ch in chars:
                ids_ch = base_tok(ch, add_special_tokens=False)["input_ids"]
                base_ids.extend([i for i in ids_ch if i < old_vocab_size])

        if len(base_ids) == 0:
            # ешқандай мәнді mapping шықпаса, моделдің random init-ін қалдырамыз
            continue

        # 3) Претренед эмбеддингтерінің орташа мәні
        base_vec = weight_kz[base_ids].mean(dim=0)

        # 4) Нормасын оригинал орташа нормаға келтіру (distribution alignment)
        vec_norm = base_vec.norm().item()
        if vec_norm > 0:
            base_vec = base_vec / vec_norm * avg_norm

        weight_kz[new_id] = base_vec

print("✅ Жаңа Kazakh токендер pretrained эмбеддингтерден (мағыналы схема) инициализацияланды.")

pooling_model_kz = models.Pooling(
    word_embedding_model_kz.get_word_embedding_dimension(),
    pooling_mode_mean_tokens=True,
    pooling_mode_cls_token=False,
    pooling_mode_max_tokens=False,
)

st_model_kz = SentenceTransformer(
    modules=[word_embedding_model_kz, pooling_model_kz],
    device=DEVICE
)

print("✅ Kazakh токенизаторымен біріктірілген ST моделі дайын.")
st_model_kz.save(KZ_ST_DIR)
print(f"💾 KAZ-CLEAN модель сақталды: {KZ_ST_DIR}")

def _encode_retr_kz(texts, batch_size=32, normalize=False, do_segment=False):
    """
    KAZ-CLEAN retrieval:
    - do_segment=False → clean view
    - do_segment=True  → SPM сегменттелген view (dual-view үшін)
    """
    if do_segment:
        texts = [segment_text(t) for t in texts]

    with torch.inference_mode():
        vecs = st_model_kz.encode(
            texts,
            batch_size=batch_size,
            convert_to_numpy=True,
            normalize_embeddings=normalize
        )
    return vecs

# ============================================================
# C) MT5-CLEAN: mT5 токенизаторы, single-view (архитектура)
#    Dual-view тек retrieval деңгейінде (clean + segmented Q→Q)
#    Барлық mT5 токендер MiniLM pretrained эмбеддингтерден мағыналы инициализацияланады
# ============================================================
print("\n=== [MT5-CLEAN] mT5 tokenizer, single-view (arch), Q→Q ===")
print("🔍 mT5 токенизаторын жүктеу:", MT5_MODEL_NAME)
mt5_tok = AutoTokenizer.from_pretrained(MT5_MODEL_NAME)
mt5_tok.save_pretrained(MT5_TOK_DIR)
print("✅ mT5 токенизаторы файлдары жазылды →", MT5_TOK_DIR)

print("⬇️ MiniLM encoder-ін жүктеу және mT5 токенизаторымен байланыстыру:", SENTENCE_T_NAME)
word_embedding_model_mt5 = models.Transformer(
    SENTENCE_T_NAME,
    tokenizer_name_or_path=MT5_TOK_DIR
)

auto_model_mt5 = word_embedding_model_mt5.auto_model
auto_model_mt5.resize_token_embeddings(len(mt5_tok))

emb_layer_mt5 = auto_model_mt5.get_input_embeddings()
mt5_vocab      = mt5_tok.get_vocab()          # token -> id

with torch.no_grad():
    weight_mt5 = emb_layer_mt5.weight.data
    mt5_vocab_size = weight_mt5.size(0)
    base_dim       = base_weight_full.size(1)

    # Оригинал MiniLM эмбеддингтерінің нормаларын қолданамыз
    base_norms_mt5 = base_weight_full.norm(dim=1)
    avg_norm_mt5   = base_norms_mt5.mean().item()
    print(f"🔧 [mT5] Вокаб өлшемі: {mt5_vocab_size}")
    print(f"🔧 [mT5] Оригинал эмбеддинг нормаларының орташа мәні: {avg_norm_mt5:.4f}")

    for tok_str, new_id in mt5_vocab.items():
        if new_id >= mt5_vocab_size:
            continue

        # Егер бұл токен MiniLM вокабында болса – тура mapping
        if tok_str in base_vocab:
            base_id = base_vocab[tok_str]
            if base_id < base_weight_full.size(0):
                weight_mt5[new_id] = base_weight_full[base_id]
            continue

        # Текстік токендер үшін – семантикалық инициализация
        piece_text = tok_str.replace("▁", " ").strip()
        # Арнайы токендерге мән бермей қоямыз
        if not piece_text or tok_str.startswith("<") and tok_str.endswith(">"):
            continue

        base_ids = base_tok(
            piece_text,
            add_special_tokens=False
        )["input_ids"]
        base_ids = [i for i in base_ids if i < base_weight_full.size(0)]

        if len(base_ids) == 0:
            chars = list(piece_text)
            for ch in chars:
                ids_ch = base_tok(ch, add_special_tokens=False)["input_ids"]
                base_ids.extend([i for i in ids_ch if i < base_weight_full.size(0)])

        if len(base_ids) == 0:
            # random init қалдырамыз
            continue

        base_vec = base_weight_full[base_ids].mean(dim=0)
        vec_norm = base_vec.norm().item()
        if vec_norm > 0:
            base_vec = base_vec / vec_norm * avg_norm_mt5

        weight_mt5[new_id] = base_vec

print("✅ Барлық mT5 токендер MiniLM pretrained эмбеддингтерінен мағыналы инициализацияланды.")

pooling_model_mt5 = models.Pooling(
    word_embedding_model_mt5.get_word_embedding_dimension(),
    pooling_mode_mean_tokens=True,
    pooling_mode_cls_token=False,
    pooling_mode_max_tokens=False,
)

st_model_mt5 = SentenceTransformer(
    modules=[word_embedding_model_mt5, pooling_model_mt5],
    device=DEVICE
)

print("✅ mT5 токенизаторымен біріктірілген ST моделі дайын.")
st_model_mt5.save(MT5_ST_DIR)
print(f"💾 MT5-CLEAN модель сақталды: {MT5_ST_DIR}")

def _encode_retr_mt5(texts, batch_size=32, normalize=False, do_segment=False):
    """
    MT5-CLEAN retrieval:
    - do_segment=False → clean view
    - do_segment=True  → SPM сегменттелген view (dual-view үшін)
    """
    if do_segment:
        texts = [segment_text(t) for t in texts]

    with torch.inference_mode():
        vecs = st_model_mt5.encode(
            texts,
            batch_size=batch_size,
            convert_to_numpy=True,
            normalize_embeddings=normalize
        )
    return vecs

# ============================================================
# 3) Fine-tune конфигурациясы (үш модельге де ортақ, қазір OFF)
# ============================================================

BATCH_SIZE = 16
EPOCHS     = 5
WARMUP_PCT = 0.1
LR         = 1e-5

train_examples = [
    InputExample(texts=[row["question"], row["answer"]])
    for _, row in train_df.iterrows()
]

print("\n🧪 Fine-tune конфигурациясы (MNRL, q→a, бірақ бұл нұсқада іске қосылмайды):")
print(f"- TRAIN samples: {len(train_examples)}")
print(f"- BATCH_SIZE: {BATCH_SIZE}")
print(f"- EPOCHS: {EPOCHS}")
print(f"- LR: {LR}")

DO_FINETUNE = False  # Үш модельде де OFF (әділдік үшін)

if DO_FINETUNE:
    # Егер fine-tune жасайтын болсаңыз, baseline / KAZ / mT5 үшін бөлек loop қажет
    pass

print("⚠ Fine-tune өшірілген. Үш модель де pretrained ғана (MLM адаптация жоқ).")

# ============================================================
# 4) Бағалау моделі (ортақ, freeze)
# ============================================================
EVAL_MODEL_NAME = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
print(f"\n🔍 Бағалау моделі жүктелді (ортақ): {EVAL_MODEL_NAME}")
eval_model = SentenceTransformer(EVAL_MODEL_NAME, device=DEVICE)
eval_model.to(DEVICE)
eval_model.eval()

def _encode_eval(texts, batch_size=32, normalize=False):
    with torch.inference_mode():
        vecs = eval_model.encode(
            texts,
            batch_size=batch_size,
            convert_to_numpy=True,
            normalize_embeddings=normalize
        )
    return vecs

# ============================================================
# 5) BASELINE-CLEAN: dual-view Q→Q retrieval және метрикалар
# ============================================================
qa_questions = qa_data["question"].tolist()
qa_answers   = qa_data["answer"].tolist()

print("\n📦 [BASELINE-CLEAN] QA және TRAIN үшін CLEAN + SEGMENTED эмбеддингтерді есептеу...")
qa_q_emb_std_clean    = _encode_retr_std(qa_questions,  normalize=True, do_segment=False)
qa_q_emb_std_seg      = _encode_retr_std(qa_questions,  normalize=True, do_segment=True)
train_q_emb_std_clean = _encode_retr_std(train_questions, normalize=True, do_segment=False)
train_q_emb_std_seg   = _encode_retr_std(train_questions, normalize=True, do_segment=True)

ALPHA_SEG = 0.6  # dual-view салмағы: 0.6*seg + 0.4*clean (үш модельге де ортақ)

def _dual_view_sim_std(question: str,
                       kb_clean: np.ndarray,
                       kb_seg: np.ndarray) -> np.ndarray:
    """
    BASELINE-CLEAN dual-view similarity:
    - clean view: original text
    - segmented view: SPM сегменттелген text
    Екі view қосылып, ортақ скора есептеледі.
    """
    q_clean = _encode_retr_std([question], normalize=True, do_segment=False)
    q_seg   = _encode_retr_std([question], normalize=True, do_segment=True)

    sims_clean = (kb_clean @ q_clean.T).squeeze(1)
    sims_seg   = (kb_seg   @ q_seg.T).squeeze(1)

    sims = ALPHA_SEG * sims_seg + (1.0 - ALPHA_SEG) * sims_clean
    return sims

def ask_question_std(question, threshold=0.6):
    """
    BASELINE-CLEAN: интерактив режим (full QA KB, dual-view Q→Q).
    """
    sims = _dual_view_sim_std(
        question,
        kb_clean=qa_q_emb_std_clean,
        kb_seg=qa_q_emb_std_seg
    )
    idx = int(np.argmax(sims))
    if float(sims[idx]) < threshold:
        return "Кешіріңіз, нақты жауап табылмады.", -1
    return qa_answers[idx], idx

def ask_question_eval_std(question):
    """
    BASELINE-CLEAN: held-out бағалау (TEST Q → TRAIN KB, dual-view Q→Q).
    """
    sims = _dual_view_sim_std(
        question,
        kb_clean=train_q_emb_std_clean,
        kb_seg=train_q_emb_std_seg
    )
    idx = int(np.argmax(sims))
    return train_answers[idx], idx

def _encode_pairs_for_eval_std():
    preds, trues = [], []
    for q, true_a in zip(test_questions, test_answers):
        p, _ = ask_question_eval_std(q)
        preds.append(p)
        trues.append(true_a)
    pv = _encode_eval(preds,  normalize=False)
    tv = _encode_eval(trues, normalize=False)
    return pv, tv

def evaluate_accuracy_exact_std():
    correct = 0
    total = len(test_questions)
    for q, true_a in zip(test_questions, test_answers):
        p, _ = ask_question_eval_std(q)
        if p.strip() == true_a.strip():
            correct += 1
    return correct / total if total > 0 else 0.0

def evaluate_cosine_similarity_std():
    pv, tv = _encode_pairs_for_eval_std()
    pv = pv / np.linalg.norm(pv, axis=1, keepdims=True)
    tv = tv / np.linalg.norm(tv, axis=1, keepdims=True)
    cs = np.sum(pv * tv, axis=1)
    return float(np.mean(cs))

def evaluate_accuracy_semantic_cos_std(threshold=0.85):
    pv, tv = _encode_pairs_for_eval_std()
    pv = pv / np.linalg.norm(pv, axis=1, keepdims=True)
    tv = tv / np.linalg.norm(tv, axis=1, keepdims=True)
    cs = np.sum(pv * tv, axis=1)
    return float(np.mean(cs >= threshold))

def evaluate_bert_score_and_semantic_std(threshold=0.85, model_type="xlm-roberta-large"):
    preds, trues = [], []
    for q, true_a in zip(test_questions, test_answers):
        p, _ = ask_question_eval_std(q)
        preds.append(p)
        trues.append(true_a)

    P, R, F1 = bertscore(
        preds,
        trues,
        model_type=model_type,
        verbose=False,
        rescale_with_baseline=False,
        device=DEVICE,
    )

    sem_acc_bert = (F1 >= threshold).float().mean().item()

    return {
        "precision": P.mean().item(),
        "recall":    R.mean().item(),
        "f1":        F1.mean().item(),
        "semantic_acc_bert": sem_acc_bert,
    }

def evaluate_system_std():
    t0 = time.time()

    acc_exact   = evaluate_accuracy_exact_std()
    acc_sem_cos = evaluate_accuracy_semantic_cos_std(threshold=0.85)
    cos_sim     = evaluate_cosine_similarity_std()
    bs          = evaluate_bert_score_and_semantic_std(threshold=0.85, model_type="xlm-roberta-large")

    total_t = time.time() - t0

    print("\n=== [BASELINE-CLEAN] Бағалау нәтижелері (standard tokenizer, dual-view, fine-tune ЖОҚ) ===")
    print(f"TEST size: {len(test_df)} QA")
    print(f"Accuracy@1 (Exact):                   {acc_exact:.4f}")
    print(f"Accuracy@1 (Semantic Cosine≥0.85):    {acc_sem_cos:.4f}")
    print(f"Accuracy@1 (Semantic BERT F1≥0.85):   {bs['semantic_acc_bert']:.4f}")
    print(f"Average Cosine Similarity (EVAL):     {cos_sim:.4f}")
    print(
        f"BERTScore - Precision: {bs['precision']:.4f}, "
        f"Recall: {bs['recall']:.4f}, F1: {bs['f1']:.4f}"
    )
    print(f"Бағалау уақыты: {total_t:.2f} секунд")

# ============================================================
# 6) KAZ-CLEAN: dual-view Q→Q retrieval және метрикалар
# ============================================================

print("\n📦 [KAZ-CLEAN] QA және TRAIN үшін CLEAN + SEGMENTED эмбеддингтерді есептеу...")
qa_q_emb_kz_clean    = _encode_retr_kz(qa_questions,  normalize=True, do_segment=False)
qa_q_emb_kz_seg      = _encode_retr_kz(qa_questions,  normalize=True, do_segment=True)
train_q_emb_kz_clean = _encode_retr_kz(train_questions, normalize=True, do_segment=False)
train_q_emb_kz_seg   = _encode_retr_kz(train_questions, normalize=True, do_segment=True)

def _dual_view_sim_kz(question: str,
                      kb_clean: np.ndarray,
                      kb_seg: np.ndarray) -> np.ndarray:
    """
    KAZ-CLEAN dual-view similarity:
    - clean view: original text
    - segmented view: SPM сегменттелген text
    """
    q_clean = _encode_retr_kz([question], normalize=True, do_segment=False)
    q_seg   = _encode_retr_kz([question], normalize=True, do_segment=True)

    sims_clean = (kb_clean @ q_clean.T).squeeze(1)
    sims_seg   = (kb_seg   @ q_seg.T).squeeze(1)

    sims = ALPHA_SEG * sims_seg + (1.0 - ALPHA_SEG) * sims_clean
    return sims

def ask_question_kz(question, threshold=0.6):
    """
    KAZ-CLEAN: интерактив режим (full QA KB, dual-view Q→Q, Kazakh tokenizer).
    """
    sims = _dual_view_sim_kz(
        question,
        kb_clean=qa_q_emb_kz_clean,
        kb_seg=qa_q_emb_kz_seg
    )
    idx = int(np.argmax(sims))
    if float(sims[idx]) < threshold:
        return "Кешіріңіз, нақты жауап табылмады.", -1
    return qa_answers[idx], idx

def ask_question_eval_kz(question):
    """
    KAZ-CLEAN: held-out бағалау (TEST Q → TRAIN KB, dual-view Q→Q, Kazakh tokenizer).
    """
    sims = _dual_view_sim_kz(
        question,
        kb_clean=train_q_emb_kz_clean,
        kb_seg=train_q_emb_kz_seg
    )
    idx = int(np.argmax(sims))
    return train_answers[idx], idx

def _encode_pairs_for_eval_kz():
    preds, trues = [], []
    for q, true_a in zip(test_questions, test_answers):
        p, _ = ask_question_eval_kz(q)
        preds.append(p)
        trues.append(true_a)
    pv = _encode_eval(preds,  normalize=False)
    tv = _encode_eval(trues, normalize=False)
    return pv, tv

def evaluate_accuracy_exact_kz():
    correct = 0
    total = len(test_questions)
    for q, true_a in zip(test_questions, test_answers):
        p, _ = ask_question_eval_kz(q)
        if p.strip() == true_a.strip():
            correct += 1
    return correct / total if total > 0 else 0.0

def evaluate_cosine_similarity_kz():
    pv, tv = _encode_pairs_for_eval_kz()
    pv = pv / np.linalg.norm(pv, axis=1, keepdims=True)
    tv = tv / np.linalg.norm(tv, axis=1, keepdims=True)
    cs = np.sum(pv * tv, axis=1)
    return float(np.mean(cs))

def evaluate_accuracy_semantic_cos_kz(threshold=0.85):
    pv, tv = _encode_pairs_for_eval_kz()
    pv = pv / np.linalg.norm(pv, axis=1, keepdims=True)
    tv = tv / np.linalg.norm(tv, axis=1, keepdims=True)
    cs = np.sum(pv * tv, axis=1)
    return float(np.mean(cs >= threshold))

def evaluate_bert_score_and_semantic_kz(threshold=0.85, model_type="xlm-roberta-large"):
    preds, trues = [], []
    for q, true_a in zip(test_questions, test_answers):
        p, _ = ask_question_eval_kz(q)
        preds.append(p)
        trues.append(true_a)

    P, R, F1 = bertscore(
        preds,
        trues,
        model_type=model_type,
        verbose=False,
        rescale_with_baseline=False,
        device=DEVICE,
    )

    sem_acc_bert = (F1 >= threshold).float().mean().item()

    return {
        "precision": P.mean().item(),
        "recall":    R.mean().item(),
        "f1":        F1.mean().item(),
        "semantic_acc_bert": sem_acc_bert,
    }

def evaluate_system_kz():
    t0 = time.time()

    acc_exact   = evaluate_accuracy_exact_kz()
    acc_sem_cos = evaluate_accuracy_semantic_cos_kz(threshold=0.85)
    cos_sim     = evaluate_cosine_similarity_kz()
    bs          = evaluate_bert_score_and_semantic_kz(threshold=0.85, model_type="xlm-roberta-large")

    total_t = time.time() - t0

    print("\n=== [KAZ-CLEAN] Бағалау нәтижелері (Kazakh tokenizer, dual-view, fine-tune ЖОҚ) ===")
    print(f"TEST size: {len(test_df)} QA")
    print(f"Accuracy@1 (Exact):                   {acc_exact:.4f}")
    print(f"Accuracy@1 (Semantic Cosine≥0.85):    {acc_sem_cos:.4f}")
    print(f"Accuracy@1 (Semantic BERT F1≥0.85):   {bs['semantic_acc_bert']:.4f}")
    print(f"Average Cosine Similarity (EVAL):     {cos_sim:.4f}")
    print(
        f"BERTScore - Precision: {bs['precision']:.4f}, "
        f"Recall: {bs['recall']:.4f}, F1: {bs['f1']:.4f}"
    )
    print(f"Бағалау уақыты: {total_t:.2f} секунд")

# ============================================================
# 7) MT5-CLEAN: dual-view Q→Q retrieval және метрикалар
# ============================================================

print("\n📦 [MT5-CLEAN] QA және TRAIN үшін CLEAN + SEGMENTED эмбеддингтерді есептеу...")
qa_q_emb_mt5_clean    = _encode_retr_mt5(qa_questions,  normalize=True, do_segment=False)
qa_q_emb_mt5_seg      = _encode_retr_mt5(qa_questions,  normalize=True, do_segment=True)
train_q_emb_mt5_clean = _encode_retr_mt5(train_questions, normalize=True, do_segment=False)
train_q_emb_mt5_seg   = _encode_retr_mt5(train_questions, normalize=True, do_segment=True)

def _dual_view_sim_mt5(question: str,
                       kb_clean: np.ndarray,
                       kb_seg: np.ndarray) -> np.ndarray:
    """
    MT5-CLEAN dual-view similarity:
    - clean view: original text
    - segmented view: SPM сегменттелген text
    """
    q_clean = _encode_retr_mt5([question], normalize=True, do_segment=False)
    q_seg   = _encode_retr_mt5([question], normalize=True, do_segment=True)

    sims_clean = (kb_clean @ q_clean.T).squeeze(1)
    sims_seg   = (kb_seg   @ q_seg.T).squeeze(1)

    sims = ALPHA_SEG * sims_seg + (1.0 - ALPHA_SEG) * sims_clean
    return sims

def ask_question_mt5(question, threshold=0.6):
    """
    MT5-CLEAN: интерактив режим (full QA KB, dual-view Q→Q, mT5 tokenizer).
    """
    sims = _dual_view_sim_mt5(
        question,
        kb_clean=qa_q_emb_mt5_clean,
        kb_seg=qa_q_emb_mt5_seg
    )
    idx = int(np.argmax(sims))
    if float(sims[idx]) < threshold:
        return "Кешіріңіз, нақты жауап табылмады.", -1
    return qa_answers[idx], idx

def ask_question_eval_mt5(question):
    """
    MT5-CLEAN: held-out бағалау (TEST Q → TRAIN KB, dual-view Q→Q, mT5 tokenizer).
    """
    sims = _dual_view_sim_mt5(
        question,
        kb_clean=train_q_emb_mt5_clean,
        kb_seg=train_q_emb_mt5_seg
    )
    idx = int(np.argmax(sims))
    return train_answers[idx], idx

def _encode_pairs_for_eval_mt5():
    preds, trues = [], []
    for q, true_a in zip(test_questions, test_answers):
        p, _ = ask_question_eval_mt5(q)
        preds.append(p)
        trues.append(true_a)
    pv = _encode_eval(preds,  normalize=False)
    tv = _encode_eval(trues, normalize=False)
    return pv, tv

def evaluate_accuracy_exact_mt5():
    correct = 0
    total = len(test_questions)
    for q, true_a in zip(test_questions, test_answers):
        p, _ = ask_question_eval_mt5(q)
        if p.strip() == true_a.strip():
            correct += 1
    return correct / total if total > 0 else 0.0

def evaluate_cosine_similarity_mt5():
    pv, tv = _encode_pairs_for_eval_mt5()
    pv = pv / np.linalg.norm(pv, axis=1, keepdims=True)
    tv = tv / np.linalg.norm(tv, axis=1, keepdims=True)
    cs = np.sum(pv * tv, axis=1)
    return float(np.mean(cs))

def evaluate_accuracy_semantic_cos_mt5(threshold=0.85):
    pv, tv = _encode_pairs_for_eval_mt5()
    pv = pv / np.linalg.norm(pv, axis=1, keepdims=True)
    tv = tv / np.linalg.norm(tv, axis=1, keepdims=True)
    cs = np.sum(pv * tv, axis=1)
    return float(np.mean(cs >= threshold))

def evaluate_bert_score_and_semantic_mt5(threshold=0.85, model_type="xlm-roberta-large"):
    preds, trues = [], []
    for q, true_a in zip(test_questions, test_answers):
        p, _ = ask_question_eval_mt5(q)
        preds.append(p)
        trues.append(true_a)

    P, R, F1 = bertscore(
        preds,
        trues,
        model_type=model_type,
        verbose=False,
        rescale_with_baseline=False,
        device=DEVICE,
    )

    sem_acc_bert = (F1 >= threshold).float().mean().item()

    return {
        "precision": P.mean().item(),
        "recall":    R.mean().item(),
        "f1":        F1.mean().item(),
        "semantic_acc_bert": sem_acc_bert,
    }

def evaluate_system_mt5():
    t0 = time.time()

    acc_exact   = evaluate_accuracy_exact_mt5()
    acc_sem_cos = evaluate_accuracy_semantic_cos_mt5(threshold=0.85)
    cos_sim     = evaluate_cosine_similarity_mt5()
    bs          = evaluate_bert_score_and_semantic_mt5(threshold=0.85, model_type="xlm-roberta-large")

    total_t = time.time() - t0

    print("\n=== [MT5-CLEAN] Бағалау нәтижелері (mT5 tokenizer, dual-view, fine-tune ЖОҚ) ===")
    print(f"TEST size: {len(test_df)} QA")
    print(f"Accuracy@1 (Exact):                   {acc_exact:.4f}")
    print(f"Accuracy@1 (Semantic Cosine≥0.85):    {acc_sem_cos:.4f}")
    print(f"Accuracy@1 (Semantic BERT F1≥0.85):   {bs['semantic_acc_bert']:.4f}")
    print(f"Average Cosine Similarity (EVAL):     {cos_sim:.4f}")
    print(
        f"BERTScore - Precision: {bs['precision']:.4f}, "
        f"Recall: {bs['recall']:.4f}, F1: {bs['f1']:.4f}"
    )
    print(f"Бағалау уақыты: {total_t:.2f} секунд")

# 🔁 Диалог + бағалау
if __name__ == "__main__":
    try:
        while True:
            user_input = input("\nСұрақ енгізіңіз (шығу үшін 'exit', baseline үшін 'b: ...', mT5 үшін 'm: ...'): ")
            txt = user_input.strip()
            if txt.lower() == "exit":
                print("Бағдарлама тоқтатылды. 👋")
                break

            # 'b:' префиксі → BASELINE-CLEAN (dual-view)
            if txt.lower().startswith("b:"):
                q = txt[2:].strip()
                answer, idx = ask_question_std(q)
                print("\n=== [BASELINE-CLEAN ЖАУАП] ===")
                print(answer)
                print(f"(idx={idx})")

            # 'm:' префиксі → MT5-CLEAN (dual-view)
            elif txt.lower().startswith("m:"):
                q = txt[2:].strip()
                answer, idx = ask_question_mt5(q)
                print("\n=== [MT5-CLEAN ЖАУАП] ===")
                print(answer)
                print(f"(idx={idx})")

            # әдепкіде → KAZ-CLEAN (dual-view)
            else:
                answer, idx = ask_question_kz(txt)
                print("\n=== [KAZ-CLEAN ЖАУАП] ===")
                print(answer)
                print(f"(idx={idx})")
    except EOFError:
        pass

    # Үш жүйені де бірдей held-out TEST-та бағалаймыз
    evaluate_system_std()
    evaluate_system_kz()
    evaluate_system_mt5()