# -*- coding: utf-8 -*-
"""femseg

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13febAkjJ5QZzkNOn9L4h8A0LZuo26f1Z
"""

# @title
!pip install bert-score
!pip install datasets
!pip install sentence-transformers datasets accelerate transformers wandb
!pip install sentence-transformers torch sklearn bert-score
!pip install sentencepiece
!pip install -q sentencepiece transformers sentence-transformers bert-score torch scikit-learn pandas numpy
!pip install -q pytorch-crf

"""femseg1"""

# @title
# ============================================================
# paraphrase-multilingual-MiniLM-L12-v2 + FEMSeg_v3 → (SPM жоқ)
# MLM жоқ, held-out TEST, FINE-TUNE ЖОҚ, dual-view (эмбеддинг деңгейінде)
# РЕТ:
#   0) FEMSeg_v3 (KazMorphSegmentor)
#   1) FEMSeg сегменттелген мәтін → MiniLM (өз токенизаторы)
#   2) Fine-tune ЖОҚ (pretrained MiniLM + FEMSeg)
#   3) Dual-view retrieval (эмбеддинг деңгейінде):
#      - v_seg  = encode(FEMSeg_sp(text))
#      - v_clean= encode(clean text)
#      - v_dual = ALPHA_SEG * v_seg + (1-ALPHA_SEG) * v_clean
#   4) Метрикалар (реалистік, held-out TEST):
#      - Accuracy@1 (Exact)
#      - Accuracy@1 (Semantic Cosine ≥ 0.85) [EVAL модель]
#      - Accuracy@1 (Semantic BERT F1 ≥ 0.85) [BERTScore]
#      - Average Cosine Similarity (EVAL)
#      - BERTScore Precision / Recall / F1
# ============================================================

# ENV
import os
os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"
os.environ["WANDB_DISABLED"] = "true"

import time, random, json
from pathlib import Path
from typing import List, Dict

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader

import sentencepiece as spm
import json  # JSON датасетін оқу үшін       # Енді қолданылмайды, бірақ импорт тұрғаны қорқыныш емес
from bert_score import score as bertscore
from torchcrf import CRF
from tokenizers import Tokenizer   # Енді қолданылмайды
from tokenizers.models import Unigram
from tokenizers.processors import TemplateProcessing
from tokenizers.pre_tokenizers import Metaspace as PreMS
from tokenizers.decoders import Metaspace as DecMS

from transformers import (
    PreTrainedTokenizerFast,       # Енді қолданылмайды
    set_seed,
)

from sentence_transformers import SentenceTransformer, InputExample, losses, models
from google.colab import drive
from sklearn.model_selection import train_test_split

# --------------------------
# 🔒 Детерминизм
# --------------------------
SEED = 42
set_seed(SEED)
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

torch.use_deterministic_algorithms(True)
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = True

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("🖥 DEVICE:", DEVICE)

# --------------------------
# ⚙️ Dual-view конфигурациясы
# --------------------------
# v_dual = ALPHA_SEG * v_seg + (1 - ALPHA_SEG) * v_clean
ALPHA_SEG = 0.6  # қолмен қойылған салмақ (segmented view басым)

# =========================
# 0) QA деректері – JSON файлдан оқу
# =========================
# Күтілетін формат (line-delimited JSON):
# {"question": "...", "answer": "..."}
# {"question": "...", "answer": "..."}
# ...

DATA_JSON_PATH = "qa_data.json"  # керек болса /content/drive/... деп толық жолға ауыстырыңыз

if not Path(DATA_JSON_PATH).is_file():
    raise FileNotFoundError(f"QA JSON файлы табылмады: {DATA_JSON_PATH}")

print(f"📥 QA JSON файлдан жүктеу: {DATA_JSON_PATH}")

data = []
with open(DATA_JSON_PATH, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue

        # Соңында үтір тұрған болса, алып тастаймыз: {...},
        if line.endswith(","):
            line = line[:-1].strip()

        # Алдымен тікелей parse жасап көреміз
        try:
            obj = json.loads(line)
        except json.JSONDecodeError as e:
            # Егер Invalid \escape қатесі болса — backslash-тарды escape жасаймыз
            if "Invalid \\escape" in str(e):
                fixed_line = line.replace("\\", "\\\\")
                obj = json.loads(fixed_line)
            else:
                raise
        data.append(obj)

# Күтілетін формат: [{"question": "...", "answer": "..."}, ...]
qa_data = pd.DataFrame(data)
assert {"question", "answer"}.issubset(qa_data.columns), "JSON-да 'question' және 'answer' бағандары болуы тиіс."

print(f"📚 Барлық QA жазба саны: {len(qa_data)}")

# ============================================================
# 0) FEMSeg_v3 (KazMorphSegmentor) – Бірінші қадам
# ============================================================

BMES_TAGS = ["B", "M", "E", "S"]
TAG2ID = {t: i for i, t in enumerate(BMES_TAGS)}
ID2TAG = {i: t for t, i in TAG2ID.items()}


class FEMSegV3(nn.Module):
    def __init__(
        self,
        vocab_size: int,
        char_emb_dim: int = 128,
        lstm_hidden_dim: int = 256,
        dropout: float = 0.3,
        num_tags: int = len(BMES_TAGS),
    ):
        super().__init__()

        self.emb = nn.Embedding(vocab_size, char_emb_dim, padding_idx=0)

        self.lstm = nn.LSTM(
            input_size=char_emb_dim,
            hidden_size=lstm_hidden_dim,
            num_layers=1,
            batch_first=True,
            bidirectional=True,
        )

        self.fc = nn.Linear(lstm_hidden_dim * 2, num_tags)
        self.crf = CRF(num_tags, batch_first=True)
        self.dropout = nn.Dropout(dropout)

    def forward_features(self, x: torch.Tensor, mask: torch.Tensor) -> torch.Tensor:
        emb = self.emb(x)
        emb = self.dropout(emb)
        h, _ = self.lstm(emb)
        h = self.dropout(h)
        return h

    def forward_logits(self, x: torch.Tensor, mask: torch.Tensor) -> torch.Tensor:
        feats = self.forward_features(x, mask)
        emissions = self.fc(feats)
        return emissions

    def forward(
        self,
        x: torch.Tensor,
        tags: torch.Tensor = None,
        mask: torch.Tensor = None,
    ):
        if mask is None:
            mask = x != 0

        emissions = self.forward_logits(x, mask)

        if tags is not None:
            loss = -self.crf(emissions, tags, mask=mask, reduction="mean")
            return loss

        best_paths = self.crf.decode(emissions, mask=mask)
        return best_paths


def bmes_to_cse(chars: List[str], tags: List[str]) -> str:
    morphs: List[str] = []
    cur = ""

    for ch, t in zip(chars, tags):
        if t == "B":
            if cur:
                morphs.append(cur)
            cur = ch
        elif t == "M":
            cur += ch
        elif t == "E":
            cur += ch
            morphs.append(cur)
            cur = ""
        elif t == "S":
            if cur:
                morphs.append(cur)
            morphs.append(ch)
            cur = ""

    if cur:
        morphs.append(cur)

    return "@@ ".join(morphs)


class KazMorphSegmentor:
    def __init__(
        self,
        char2id_path: str,
        ckpt_path: str,
        use_cuda: bool = True,
    ):
        with open(char2id_path, "r", encoding="utf-8") as f:
            self.char2id: Dict[str, int] = json.load(f)

        self.pad_id = 0
        self.unk_id = (
            self.char2id.get("<unk>")
            or self.char2id.get("[UNK]")
            or 1
        )

        self.device = torch.device(
            "cuda" if (use_cuda and torch.cuda.is_available()) else "cpu"
        )

        vocab_size = max(self.char2id.values()) + 1

        self.model = FEMSegV3(vocab_size=vocab_size)
        self.model.to(self.device)

        state = torch.load(ckpt_path, map_location=self.device)
        if isinstance(state, dict):
            if "state_dict" in state:
                state = state["state_dict"]
            elif "model_state_dict" in state:
                state = state["model_state_dict"]

        if isinstance(state, dict) and any(k.startswith("module.") for k in state.keys()):
            state = {k.replace("module.", "", 1): v for k, v in state.items()}

        self.model.load_state_dict(state, strict=True)
        self.model.eval()

    def _word_to_tensor(self, word: str):
        ids = [
            self.char2id.get(ch, self.unk_id)
            for ch in list(word)
        ]
        x = torch.tensor([ids], dtype=torch.long, device=self.device)
        mask = (x != self.pad_id)
        return x, mask

    def segment_word(self, word: str) -> str:
        word = word.strip()
        if not word:
            return ""

        x, mask = self._word_to_tensor(word)
        with torch.no_grad():
            best_paths = self.model(x, mask=mask)

        tag_ids = best_paths[0]
        tags = [ID2TAG[i] for i in tag_ids]

        return bmes_to_cse(list(word), tags)

    def segment_text(self, text: str) -> str:
        text = text.strip()
        if not text:
            return ""

        words = text.split()
        out_words: List[str] = []

        for w in words:
            seg_w = self.segment_word(w)
            out_words.append(seg_w)

        return " | ".join(out_words)


def femseg_to_sp(text: str) -> str:
    """
    FEMSeg_v3 → морфемалар → BPE-стильдегі '▁root suffix ...'
    Назар: бұл жерде SPM vocab қажет емес, тек мәтіндік белгілеу.
    """
    text = str(text).strip()
    if not text:
        return ""

    seg_line = femseg.segment_text(text)

    sp_tokens = []
    for word_seg in seg_line.split(" | "):
        word_seg = word_seg.strip()
        if not word_seg:
            continue

        morphs = [m.strip() for m in word_seg.split("@@ ") if m.strip()]
        if not morphs:
            continue

        sp_tokens.append("▁" + morphs[0])
        sp_tokens.extend(morphs[1:])

    return " ".join(sp_tokens)


# --------- FEMSeg_v3 инстанциясы (бірінші) ----------
drive.mount("/content/drive", force_remount=True)

FEMSEG_CHAR2ID = "/content/drive/MyDrive/KAZ_MORPH/char2id_femseg_v3_50k.json"
FEMSEG_CKPT    = "/content/drive/MyDrive/KAZ_MORPH/femseg_v3_50k_epoch3.pt"

assert os.path.exists(FEMSEG_CHAR2ID), f"char2id_femseg_v3_50k.json табылмады: {FEMSEG_CHAR2ID}"
assert os.path.exists(FEMSEG_CKPT),    f"femseg_v3_50k_epoch3.pt табылмады: {FEMSEG_CKPT}"

print("⬇️ FEMSeg_v3 сегментаторын жүктеу...")
femseg = KazMorphSegmentor(
    char2id_path=FEMSEG_CHAR2ID,
    ckpt_path=FEMSEG_CKPT,
    use_cuda=True,
)
print("✅ FEMSeg_v3 дайын.")
print("🔎 FEMSeg тест:", femseg_to_sp("Мен мектепке барамын"))

# ============================================================
# Жобаның жолдары
# ============================================================
PROJECT_DIR  = "/content/kz_minilm_st_direct_spm"
LOCAL_ST_DIR = f"{PROJECT_DIR}/st_femseg_work"
ST_OUT_DIR   = f"{PROJECT_DIR}/st_femseg_pretrained"

Path(PROJECT_DIR).mkdir(parents=True, exist_ok=True)
Path(LOCAL_ST_DIR).mkdir(parents=True, exist_ok=True)
Path(ST_OUT_DIR).mkdir(parents=True, exist_ok=True)

# ============================================================
# 1) MiniLM SentenceTransformer (SPM жоқ, өз токенизаторы) – Екінші қадам
# ============================================================
SENTENCE_T_NAME = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
print("⬇️ MiniLM encoder-ін жүктеу (стандартты токенизатормен):", SENTENCE_T_NAME)

word_embedding_model = models.Transformer(
    SENTENCE_T_NAME,   # tokenizer_name_or_path бермейміз → өз токенизаторын қолданады
)

pooling_model = models.Pooling(
    word_embedding_model.get_word_embedding_dimension(),
    pooling_mode_mean_tokens=True,
    pooling_mode_cls_token=False,
    pooling_mode_max_tokens=False,
)

st_model = SentenceTransformer(
    modules=[word_embedding_model, pooling_model],
    device=DEVICE
)

print("✅ FEMSeg сегменттелген мәтінмен қолданылатын ST (MiniLM) моделі дайын.")
st_model.save(LOCAL_ST_DIR)
print(f"💾 Бастапқы (pre-finetune) модель сақталды → {LOCAL_ST_DIR}")

# FEMSeg сегменттелген мәтіндер (debug үшін)
qa_data["q_sp"] = qa_data["question"].apply(femseg_to_sp)
qa_data["a_sp"] = qa_data["answer"].apply(femseg_to_sp)

print("\n🔎 Мысал (q / q_sp / a / a_sp):")
print(qa_data[["question", "q_sp", "answer", "a_sp"]].head())

# ============================================================
# TRAIN / TEST SPLIT (held-out)
# ============================================================
train_df, test_df = train_test_split(
    qa_data,
    test_size=0.1,
    random_state=SEED,
    shuffle=True,
)

print(f"📊 TRAIN: {len(train_df)} | TEST: {len(test_df)}")

train_questions = train_df["question"].tolist()
train_answers   = train_df["answer"].tolist()
test_questions  = test_df["question"].tolist()
test_answers    = test_df["answer"].tolist()

# ============================================================
# Fine-tune блогы (есептеледі, бірақ FINE-TUNE ЖОҚ)
# ============================================================

BATCH_SIZE = 16
EPOCHS     = 5
WARMUP_PCT = 0.1
LR         = 1e-5   # ұзағырақ тренинг үшін кіші LR

train_samples: List[InputExample] = []
for q, a in zip(train_questions, train_answers):
    q_sp = femseg_to_sp(q)
    a_sp = femseg_to_sp(a)
    train_samples.append(InputExample(texts=[q_sp, a_sp]))

train_dataloader = DataLoader(
    train_samples,
    shuffle=True,
    batch_size=BATCH_SIZE,
)

train_loss = losses.MultipleNegativesRankingLoss(st_model)

num_train_steps = len(train_dataloader) * EPOCHS
warmup_steps = int(num_train_steps * WARMUP_PCT)

print("\n🧪 FINE-TUNE (FEMSeg+MiniLM, q→a, MNRL) конфигурациясы (есептелді, бірақ орындалмайды):")
print(f"- TRAIN samples: {len(train_samples)}")
print(f"- BATCH_SIZE: {BATCH_SIZE}")
print(f"- EPOCHS (план): {EPOCHS}")
print(f"- TOTAL STEPS: {num_train_steps}")
print(f"- WARMUP STEPS: {warmup_steps}")
print(f"- LR: {LR}")

print("⚠ Fine-tune өшірілген: st_model pretrained (fine-tune ЖОҚ) күйінде қолданылады.")
st_model.save(ST_OUT_DIR)
print(f"💾 (Fine-tune ЖОҚ) ST модель сақталды: {ST_OUT_DIR}")

# ============================================================
# Retrieval моделі: PRETRAINED ST (FEMSeg dual-view үшін)
# ============================================================

retr_model = st_model
retr_model.to(DEVICE)
retr_model.eval()

# --------- Бағалау үшін freeze MiniLM (EVAL модель) ----------
EVAL_MODEL_NAME = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
print(f"🔍 Бағалау моделі жүктелді (EVAL): {EVAL_MODEL_NAME}")
eval_model = SentenceTransformer(EVAL_MODEL_NAME, device=DEVICE)
eval_model.to(DEVICE)
eval_model.eval()

# ============================================================
# Энкодер көмекші функциялары (dual-view EMB деңгейінде)
# ============================================================

def _encode_retr(texts, batch_size=32, normalize=True):
    """
    Retrieval үшін эмбеддинг (dual-view, эмбеддинг деңгейінде):
      - v_seg   = encode(FEMSeg_sp(text))
      - v_clean = encode(clean text)
      - v_dual  = ALPHA_SEG * v_seg + (1-ALPHA_SEG) * v_clean
    """
    texts = [str(t) for t in texts]
    texts_sp = [femseg_to_sp(t) for t in texts]

    with torch.inference_mode():
        # 1) segmented view
        v_seg = retr_model.encode(
            texts_sp,
            batch_size=batch_size,
            convert_to_numpy=True,
            normalize_embeddings=False,
        )

        # 2) clean view
        v_clean = retr_model.encode(
            texts,
            batch_size=batch_size,
            convert_to_numpy=True,
            normalize_embeddings=False,
        )

        vecs = ALPHA_SEG * v_seg + (1.0 - ALPHA_SEG) * v_clean

        if normalize:
            norms = np.linalg.norm(vecs, axis=1, keepdims=True) + 1e-12
            vecs = vecs / norms

    return vecs


def _encode_eval(texts, batch_size=32, normalize=False):
    """
    Бағалау үшін эмбеддинг (freeze MiniLM, segmentation-сыз).
    Мұнда таза сұрақ/жауап мәтіндері беріледі.
    """
    texts = [str(t) for t in texts]
    with torch.inference_mode():
        vecs = eval_model.encode(
            texts,
            batch_size=batch_size,
            convert_to_numpy=True,
            normalize_embeddings=normalize,
        )
    return vecs

# --------- KB эмбеддингтері (dual-view EMB) ---------

qa_questions_full = qa_data["question"].tolist()
qa_answers_full   = qa_data["answer"].tolist()

print("\n📦 QA және TRAIN үшін dual-view эмбеддингтерді есептеу...")
qa_q_emb_dual    = _encode_retr(qa_questions_full, normalize=True)
train_q_emb_dual = _encode_retr(train_questions, normalize=True)

# ============================================================
# Retrieval функциялары (dual-view Q→Q)
# ============================================================

def _retrieve_from_kb_dual(
    question: str,
    kb_q_emb: np.ndarray,
    kb_answers: list,
    threshold: float = 0.6,
):
    """
    Dual-view эмбеддинг арқылы Q→Q retrieval:
      - q_dual = _encode_retr([question])
      - sims  = kb_q_emb @ q_dual.T
    """
    qv = _encode_retr([question], normalize=True)   # [1, d]
    sims = (kb_q_emb @ qv.T).squeeze(1)            # [N]
    idx = int(np.argmax(sims))
    sim_val = float(sims[idx])
    if sim_val < threshold:
        return "Кешіріңіз, нақты жауап табылмады.", -1, sim_val
    return kb_answers[idx], idx, sim_val


def ask_question_runtime(question: str, threshold: float = 0.6):
    """
    Интерактив режим: толық QA базасынан dual-view Q→Q іздеу.
    """
    return _retrieve_from_kb_dual(
        question,
        kb_q_emb=qa_q_emb_dual,
        kb_answers=qa_answers_full,
        threshold=threshold,
    )


def ask_question_eval(question: str):
    """
    Held-out бағалау: TEST сұрағы → TRAIN KB (dual-view Q→Q).
    threshold=0.0 → reject жоқ, әрқашан ең жақын кандидат.
    """
    ans, idx, sim = _retrieve_from_kb_dual(
        question,
        kb_q_emb=train_q_emb_dual,
        kb_answers=train_answers,
        threshold=0.0,
    )
    return ans, idx, sim

# ============================================================
# Бағалауға арналған жұптар (freeze EVAL модель)
# ============================================================

def _encode_pairs_for_eval():
    """
    TEST жиыны үшін (predicted_answer, true_answer) жұптарының
    эмбеддингтерін EVAL модель арқылы есептеу.
    """
    preds, trues = [], []
    for q, true_a in zip(test_questions, test_answers):
        p, _, _ = ask_question_eval(q)
        preds.append(p)
        trues.append(true_a)

    pv = _encode_eval(preds,  normalize=False)
    tv = _encode_eval(trues, normalize=False)
    return pv, tv

# ============================================================
# МЕТРИКАЛАР (реалистік)
# ============================================================

def evaluate_accuracy_exact_femseg():
    """
    Accuracy@1 (Exact):
    Top-1 қайтарылған жауап true answer-мен жолдық деңгейде тең.
    """
    correct = 0
    total = len(test_questions)
    for q, true_a in zip(test_questions, test_answers):
        p, _, _ = ask_question_eval(q)
        if p.strip() == true_a.strip():
            correct += 1
    return correct / total if total > 0 else 0.0


def evaluate_cosine_similarity_femseg():
    """
    Average Cosine Similarity (EVAL):
    Freeze MiniLM эмбеддингтері бойынша орташа cosine(pred, true).
    """
    pv, tv = _encode_pairs_for_eval()
    pv = pv / np.linalg.norm(pv, axis=1, keepdims=True)
    tv = tv / np.linalg.norm(tv, axis=1, keepdims=True)
    cs = np.sum(pv * tv, axis=1)
    return float(np.mean(cs))


def evaluate_accuracy_semantic_cos_femseg(threshold: float = 0.85):
    """
    Accuracy@1 (Semantic Cosine ≥ threshold, EVAL модель):
    cosine(pred, true) ≥ threshold болса, сол жұп 'дұрыс' деп саналады.
    """
    pv, tv = _encode_pairs_for_eval()
    pv = pv / np.linalg.norm(pv, axis=1, keepdims=True)
    tv = tv / np.linalg.norm(tv, axis=1, keepdims=True)
    cs = np.sum(pv * tv, axis=1)
    return float(np.mean(cs >= threshold))


def evaluate_bert_score_and_semantic_femseg(
    threshold: float = 0.85,
    model_type: str = "xlm-roberta-large",
):
    """
    BERTScore (Precision / Recall / F1) және
    BERTScore F1 ≥ threshold бойынша семантикалық Accuracy@1.
    """
    preds, trues = [], []
    for q, true_a in zip(test_questions, test_answers):
        p, _, _ = ask_question_eval(q)
        preds.append(p)
        trues.append(true_a)

    P, R, F1 = bertscore(
        preds,
        trues,
        model_type=model_type,
        verbose=False,
        rescale_with_baseline=False,
        device=DEVICE,
    )

    sem_acc_bert = (F1 >= threshold).float().mean().item()

    return {
        "precision":         P.mean().item(),
        "recall":            R.mean().item(),
        "f1":                F1.mean().item(),
        "semantic_acc_bert": sem_acc_bert,
    }


def evaluate_system_femseg():
    """
    FEMSeg+MiniLM (SPM жоқ, dual-view EMB, fine-tune ЖОҚ) жүйесінің
    held-out TEST бойынша толық бағалауы.
    """
    t0 = time.time()

    acc_exact   = evaluate_accuracy_exact_femseg()
    acc_sem_cos = evaluate_accuracy_semantic_cos_femseg(threshold=0.85)
    cos_sim     = evaluate_cosine_similarity_femseg()
    bs          = evaluate_bert_score_and_semantic_femseg(
        threshold=0.85,
        model_type="xlm-roberta-large",
    )

    total_t = time.time() - t0

    print("\n=== [FEMSeg+MiniLM] Бағалау нәтижелері "
          "(SPM жоқ, held-out TEST, fine-tune ЖОҚ, dual-view EMB) ===")
    print(f"TEST size: {len(test_df)} QA")
    print(f"Accuracy@1 (Exact):                   {acc_exact:.4f}")
    print(f"Accuracy@1 (Semantic Cosine≥0.85):    {acc_sem_cos:.4f}")
    print(f"Accuracy@1 (Semantic BERT F1≥0.85):   {bs['semantic_acc_bert']:.4f}")
    print(f"Average Cosine Similarity (EVAL):     {cos_sim:.4f}")
    print(
        f"BERTScore - Precision: {bs['precision']:.4f}, "
        f"Recall: {bs['recall']:.4f}, F1: {bs['f1']:.4f}"
    )
    print(f"Бағалау уақыты: {total_t:.2f} секунд")
    print(f"ALPHA_SEG (seg vs clean): {ALPHA_SEG:.2f}")

# ============================================================
# Негізгі блок: интерактив + held-out бағалау
# ============================================================
if __name__ == "__main__":
    try:
        while True:
            user_input = input("\nСұрақ енгізіңіз (шығу үшін 'exit'): ")
            if user_input.strip().lower() == "exit":
                print("Бағдарлама тоқтатылды. 👋")
                break

            answer, idx, sim = ask_question_runtime(user_input, threshold=0.6)
            print("\n=== [FEMSeg+MiniLM ЖАУАП] ===")
            print(answer)
            print(f"(similarity={sim:.4f}, idx={idx})")
    except EOFError:
        # Colab-та stdin жабылған кезде
        pass

    # Held-out TEST бағалау
    evaluate_system_femseg()